
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Jun 04 15:12:09 CST 2022
//----------------------------------------------------

package simpl.parser;

/** CUP generated interface containing symbol constants. */
public interface Symbols {
  /* terminals */
  public static final int CONS = 33;
  public static final int ORELSE = 20;
  public static final int GE = 32;
  public static final int UNIT = 34;
  public static final int LPAREN = 40;
  public static final int SEMI = 39;
  public static final int CONTINUE = 15;
  public static final int REF = 3;
  public static final int RPAREN = 41;
  public static final int REC = 5;
  public static final int NOT = 18;
  public static final int LT = 29;
  public static final int FN = 4;
  public static final int NIL = 2;
  public static final int IN = 7;
  public static final int COMMA = 38;
  public static final int DIV = 24;
  public static final int NUM = 43;
  public static final int ASSIGN = 36;
  public static final int IF = 9;
  public static final int ID = 44;
  public static final int LE = 30;
  public static final int EOF = 0;
  public static final int APP = 42;
  public static final int TRUE = 16;
  public static final int error = 1;
  public static final int MUL = 23;
  public static final int ADD = 21;
  public static final int MOD = 25;
  public static final int BREAK = 14;
  public static final int EQ = 27;
  public static final int ARROW = 35;
  public static final int NEG = 26;
  public static final int ELSE = 11;
  public static final int ANDALSO = 19;
  public static final int WHILE = 12;
  public static final int LET = 6;
  public static final int THEN = 10;
  public static final int NE = 28;
  public static final int END = 8;
  public static final int FALSE = 17;
  public static final int GT = 31;
  public static final int SUB = 22;
  public static final int DEREF = 37;
  public static final int DO = 13;
}

