
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Jun 08 21:37:43 CST 2022
//----------------------------------------------------

package simpl.parser;

/** CUP generated interface containing symbol constants. */
public interface Symbols {
  /* terminals */
  public static final int CONS = 38;
  public static final int ORELSE = 25;
  public static final int GE = 37;
  public static final int UNIT = 39;
  public static final int CASE = 5;
  public static final int LPAREN = 45;
  public static final int SEMI = 44;
  public static final int CONTINUE = 20;
  public static final int INR = 4;
  public static final int REF = 8;
  public static final int RPAREN = 46;
  public static final int REC = 10;
  public static final int INL = 3;
  public static final int NOT = 23;
  public static final int LT = 34;
  public static final int FN = 9;
  public static final int NIL = 2;
  public static final int IN = 12;
  public static final int COMMA = 43;
  public static final int DIV = 29;
  public static final int NUM = 48;
  public static final int ASSIGN = 41;
  public static final int IF = 14;
  public static final int ID = 49;
  public static final int LE = 35;
  public static final int OF = 6;
  public static final int EOF = 0;
  public static final int APP = 47;
  public static final int TRUE = 21;
  public static final int error = 1;
  public static final int MID = 7;
  public static final int MUL = 28;
  public static final int ADD = 26;
  public static final int MOD = 30;
  public static final int BREAK = 19;
  public static final int EQ = 32;
  public static final int ARROW = 40;
  public static final int NEG = 31;
  public static final int ELSE = 16;
  public static final int ANDALSO = 24;
  public static final int WHILE = 17;
  public static final int LET = 11;
  public static final int THEN = 15;
  public static final int NE = 33;
  public static final int END = 13;
  public static final int FALSE = 22;
  public static final int GT = 36;
  public static final int SUB = 27;
  public static final int DEREF = 42;
  public static final int DO = 18;
}

